import type { Metadata } from "next";
import { Icon, type IconName } from "@/components/icon";
import { PageHero } from "@/components/page-hero";
import { Reveal } from "@/components/reveal";
export const metadata: Metadata = { title: "Services", description: "Enterprise advisory, AI, digital transformation, knowledge and product innovation services." };
const services: { title: string; description: string; icon: IconName }[] = [
  { title: "Enterprise Advisory", description: "Strategy, governance and operating model work that helps leaders frame choices and strengthen execution.", icon: "advisory" },
  { title: "AI & Intelligent Systems", description: "Practical AI and data-enabled systems designed around workflows, decisions and responsible implementation.", icon: "ai" },
  { title: "Digital Transformation", description: "Transformation programmes that connect technology choices to people, process and measurable operating change.", icon: "transform" },
  { title: "Knowledge & Leadership", description: "Leadership development and knowledge systems that turn insight into repeatable organisational capability.", icon: "leadership" },
  { title: "Product Innovation", description: "Discovery, design and development support for products and platforms that address meaningful business needs.", icon: "product" }
];
export default function Services(){const schema={"@context":"https://schema.org","@type":"ItemList",name:"UNIFLUX-D Global Services",itemListElement:services.map((service,position)=>({"@type":"Service",position:position+1,name:service.title,provider:{"@type":"Organization",name:"UNIFLUX-D Global Limited"}}))};return <main><PageHero eyebrow="Services" title="Capability for consequential work." intro="Integrated services for leaders building more intelligent, effective and resilient organisations."/><section className="container py-20 md:py-28"><div className="grid gap-8 md:grid-cols-[.75fr_1.25fr]"><p className="eyebrow">Our capabilities</p><Reveal><h2 className="display text-4xl font-semibold leading-tight">The work is interconnected. Our approach is too.</h2><p className="mt-5 leading-8 text-slate">We bring together strategic, technological and human perspectives to help organisations move from a difficult question to a more capable future.</p></Reveal></div><div className="mt-14 grid gap-4 md:grid-cols-2">{services.map((service,i)=><Reveal className={i===0?"md:col-span-2":""} key={service.title}><article className={`group flex min-h-72 flex-col justify-between p-8 transition duration-300 hover:-translate-y-1 ${i===0?"bg-navy text-white":"bg-mist hover:bg-blue hover:text-white"}`}><div className="flex items-start justify-between"><Icon name={service.icon} className={`h-7 w-7 ${i===0?"text-gold":"text-blue group-hover:text-gold"}`}/><span className="number">0{i+1}</span></div><div><h2 className="display text-3xl font-semibold">{service.title}</h2><p className={`mt-4 max-w-xl leading-7 ${i===0?"text-slate-300":"text-slate group-hover:text-blue-100"}`}>{service.description}</p></div></article></Reveal>)}</div></section><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/></main>}
