import Link from "next/link";
import { CorporateTimeline } from "@/components/corporate-timeline";
import { CorporateVisualLayer } from "@/components/corporate-visual-layer";
import { Icon } from "@/components/icon";
import { IndustryExplorer } from "@/components/industry-explorer";
import { InnovationGrid } from "@/components/innovation-grid";
import { MethodologySignature } from "@/components/methodology-signature";
import { PracticeCards } from "@/components/practice-cards";
import { Reveal } from "@/components/reveal";
import { VisualIntelligence } from "@/components/visual-intelligence";

export default function Home() { return <main>
  <section className="hero-grid overflow-hidden bg-navy py-24 text-white md:py-36"><div className="container relative"><div className="absolute -right-12 top-5 hidden h-72 w-72 rounded-full border border-blue-400/20 md:block" /><p className="eyebrow !text-gold">UNIFLUX-D GLOBAL LIMITED</p><Reveal><h1 className="display mt-6 max-w-5xl text-5xl font-semibold leading-[.94] md:text-8xl">Engineering intelligence.<br /><span className="text-blue-300">Empowering growth.</span></h1></Reveal><p className="mt-8 max-w-xl text-lg leading-8 text-slate-300">We partner with organisations to solve complex challenges through intelligent technology, operational excellence, governance and leadership development.</p><div className="mt-10 flex flex-wrap gap-4"><Link className="bg-blue px-5 py-3.5 text-sm font-semibold transition hover:bg-white hover:text-navy" href="/services">Explore our capabilities <span aria-hidden>→</span></Link><Link className="border border-white/30 px-5 py-3.5 text-sm font-semibold transition hover:border-gold hover:text-gold" href="/contact">Talk to our team</Link></div></div></section>
  <section className="container grid gap-10 py-20 md:grid-cols-[.8fr_1.2fr] md:py-28"><div><p className="eyebrow">Who we are</p></div><Reveal><h2 className="display text-4xl font-semibold leading-tight md:text-5xl">A different kind of partner for complex work.</h2><p className="mt-6 max-w-2xl leading-8 text-slate">UNIFLUX-D is an innovation, enterprise advisory, AI and knowledge company. We connect sound thinking with practical delivery to help organisations build clarity, capability and confidence.</p><Link href="/about" className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-blue hover:text-navy">More about UNIFLUX-D <Icon name="arrow" className="h-4 w-4" /></Link></Reveal></section>
  <VisualIntelligence />
  <CorporateVisualLayer />
  <section className="bg-mist py-20 md:py-28"><div className="container"><p className="eyebrow">How we help</p><h2 className="display mt-4 max-w-2xl text-4xl font-semibold md:text-5xl">Four practices. One integrated perspective.</h2><div className="mt-12"><PracticeCards /></div></div></section>
  <section className="container grid gap-10 py-20 md:grid-cols-2 md:py-28"><Reveal><p className="eyebrow">Why UNIFLUX-D</p><h2 className="display mt-4 text-4xl font-semibold leading-tight">Insight is only useful when it moves the organisation forward.</h2></Reveal><div className="space-y-7">{[["Context before solutions", "We start by understanding the system, the people and the decision at hand."], ["Rigor with relevance", "We combine disciplined frameworks with a practical view of what can be implemented."], ["Capability that endures", "Our work is designed to leave stronger teams and better ways of working behind."]].map(([t,d]) => <Reveal key={t} className="border-l-2 border-gold pl-6"><h3 className="font-display text-xl font-semibold">{t}</h3><p className="mt-2 leading-7 text-slate">{d}</p></Reveal>)}</div></section>
  <section className="bg-navy py-20 text-white md:py-28"><div className="container"><p className="eyebrow !text-gold">Innovation portfolio</p><div className="mt-5 flex flex-wrap items-end justify-between gap-5"><h2 className="display max-w-xl text-4xl font-semibold md:text-5xl">Building what tomorrow&apos;s organisations need.</h2><Link href="/innovation" className="text-sm font-bold text-white hover:text-gold">View innovation portfolio →</Link></div><InnovationGrid /></div></section>
  <section className="container py-20 md:py-28"><p className="eyebrow">Industries</p><h2 className="display mt-4 max-w-2xl text-4xl font-semibold md:text-5xl">Experience across the systems that matter.</h2><IndustryExplorer /></section>
  <MethodologySignature />
  <CorporateTimeline />
  <section className="bg-blue py-20 text-white"><div className="container flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><p className="eyebrow !text-blue-100">Start with a conversation</p><h2 className="display mt-4 max-w-2xl text-4xl font-semibold md:text-5xl">Let&apos;s make complex work clearer.</h2><p className="mt-5 max-w-xl leading-7 text-blue-100">Bring the question, the mandate or the opportunity. We will help you find a way forward.</p></div><Link href="/contact" className="inline-flex items-center gap-3 self-start bg-white px-5 py-3.5 text-sm font-bold text-navy transition hover:bg-gold md:self-auto">Contact UNIFLUX-D <Icon name="arrow" className="h-4 w-4" /></Link></div></section>
</main>; }
