import Link from "next/link";

const links = [
  ["About", "/about"], ["Services", "/services"], ["Industries", "/industries"], ["Innovation", "/innovation"], ["Methodologies", "/methodologies"], ["Leadership", "/leadership"], ["Insights", "/insights"]
];

export function Mark() { return <Link href="/" aria-label="UNIFLUX-D Global home" className="flex items-center gap-2.5"><span className="grid h-8 w-8 place-items-center bg-blue text-lg font-bold text-white">U</span><span className="font-display text-sm font-bold tracking-tight text-navy">UNIFLUX-D<br /><span className="text-[.6rem] tracking-[.19em] text-slate">GLOBAL LIMITED</span></span></Link>; }

export function Header() { return <header className="border-b border-slate-200 bg-white"><div className="container flex min-h-20 items-center justify-between gap-4"><Mark /><nav aria-label="Primary navigation" className="hidden items-center gap-5 xl:flex">{links.map(([label, href]) => <Link className="text-sm font-medium text-slate transition hover:text-blue" href={href} key={href}>{label}</Link>)}</nav><div className="hidden sm:block"><Link className="bg-navy px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-blue" href="/contact">Let&apos;s Talk <span aria-hidden>↗</span></Link></div><details className="relative xl:hidden"><summary className="cursor-pointer list-none border border-slate-300 px-3 py-2 text-sm font-semibold text-navy [&::-webkit-details-marker]:hidden">Menu <span aria-hidden>+</span></summary><nav aria-label="Mobile navigation" className="absolute right-0 z-20 mt-2 w-64 border border-slate-200 bg-white p-3 shadow-lg">{links.map(([label, href]) => <Link className="block px-3 py-2.5 text-sm font-medium text-slate hover:bg-mist hover:text-blue" href={href} key={href}>{label}</Link>)}<Link className="mt-2 block bg-navy px-3 py-2.5 text-sm font-semibold text-white sm:hidden" href="/contact">Let&apos;s Talk →</Link></nav></details></div></header>; }

export function Footer() { return <footer className="bg-navy text-white"><div className="container grid gap-12 py-14 md:grid-cols-[1.2fr_.8fr_.8fr]"><div><Mark /><p className="mt-6 max-w-sm text-sm leading-6 text-slate-300">Engineering intelligence for organisations building durable capability, responsible innovation and meaningful growth.</p></div><div><p className="text-xs font-bold tracking-[.14em] text-gold">EXPLORE</p><ul className="mt-5 space-y-3 text-sm text-slate-300">{links.slice(0,5).map(([label, href]) => <li key={href}><Link className="hover:text-white" href={href}>{label}</Link></li>)}</ul></div><div><p className="text-xs font-bold tracking-[.14em] text-gold">CONNECT</p><address className="mt-5 not-italic text-sm leading-6 text-slate-300">Flat 5A, Casino Height Apartment,<br />Yaba, Lagos, Nigeria<br /><Link className="mt-3 inline-block text-white hover:text-gold" href="/contact">Contact UNIFLUX-D →</Link></address></div></div><div className="border-t border-white/10"><div className="container flex flex-col gap-2 py-5 text-xs text-slate-400 sm:flex-row sm:justify-between"><span>© {new Date().getFullYear()} UNIFLUX-D Global Limited.</span><span>Engineering Intelligence. Empowering Growth.</span></div></div></footer>; }
