import Image from "next/image";
import Link from "next/link";

const links = [
  ["Home", "/"], ["About Us", "/about"], ["Services", "/services"], ["Industries", "/industries"], ["Innovation", "/innovation"], ["Case Studies", "/case-studies"], ["Insights", "/insights"], ["Global Opportunities", "/global-opportunities"], ["Contact", "/contact"]
];

export function Mark() {
  return <Link href="/" aria-label="UNIFLUX-D Global home" className="flex items-center shrink-0">
    <Image src="/uniflux-d-logo.svg" alt="UNIFLUX-D Global Limited — Intelligence, Innovation, Impact" width={230} height={155} className="h-14 w-[158px] object-contain sm:h-[4.6rem] sm:w-[210px]" priority />
  </Link>;
}

export function Header() { return <header className="sticky top-0 z-50 border-b border-slate-200/80 bg-white/95 backdrop-blur"><div className="container flex min-h-20 items-center justify-between gap-3"><Mark /><nav aria-label="Primary navigation" className="hidden items-center gap-3 xl:flex 2xl:gap-5">{links.map(([label, href]) => <Link className="whitespace-nowrap text-[12px] font-semibold text-navy transition hover:text-blue" href={href} key={href}>{label}</Link>)}</nav><div className="hidden sm:block"><Link className="inline-flex items-center bg-gradient-to-r from-[#f7cf6a] to-[#dcae43] px-5 py-3 text-sm font-bold text-navy shadow-sm transition hover:-translate-y-0.5 hover:shadow-md" href="/contact">Let&apos;s Talk <span aria-hidden className="ml-1">↗</span></Link></div><details className="relative xl:hidden"><summary className="cursor-pointer list-none border border-slate-300 px-3 py-2 text-sm font-semibold text-navy [&::-webkit-details-marker]:hidden">Menu <span aria-hidden>+</span></summary><nav aria-label="Mobile navigation" className="absolute right-0 z-20 mt-2 max-h-[70vh] w-72 overflow-auto border border-slate-200 bg-white p-3 shadow-xl">{links.map(([label, href]) => <Link className="block px-3 py-2.5 text-sm font-medium text-slate hover:bg-mist hover:text-blue" href={href} key={href}>{label}</Link>)}<Link className="mt-2 block bg-navy px-3 py-2.5 text-sm font-semibold text-white sm:hidden" href="/contact">Let&apos;s Talk →</Link></nav></details></div></header>; }

export function Footer() { return <footer className="bg-navy text-white"><div className="container grid gap-12 py-14 md:grid-cols-[1.2fr_.8fr_.8fr]"><div><Mark /><p className="mt-6 max-w-sm text-sm leading-6 text-slate-300">Engineering intelligence for organisations building durable capability, responsible innovation and meaningful growth.</p></div><div><p className="text-xs font-bold tracking-[.14em] text-gold">EXPLORE</p><ul className="mt-5 space-y-3 text-sm text-slate-300">{links.slice(1,6).map(([label, href]) => <li key={href}><Link className="hover:text-white" href={href}>{label}</Link></li>)}</ul></div><div><p className="text-xs font-bold tracking-[.14em] text-gold">CONNECT</p><address className="mt-5 not-italic text-sm leading-6 text-slate-300">Flat 5A, Casino Height Apartment,<br />Yaba, Lagos, Nigeria<br /><Link className="mt-3 inline-block text-white hover:text-gold" href="/contact">Contact UNIFLUX-D →</Link></address></div></div><div className="border-t border-white/10"><div className="container flex flex-col gap-2 py-5 text-xs text-slate-400 sm:flex-row sm:justify-between"><span>© {new Date().getFullYear()} UNIFLUX-D Global Limited.</span><span>Engineering Intelligence. Empowering Growth.</span></div></div></footer>; }
