import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { PublicationCard } from "@/components/publication-card";
import { PrintButton } from "@/components/print-button";
import { ReadingProgress } from "@/components/reading-progress";
import { publicationBySlug, publications, relatedPublications } from "@/lib/publications";
export function generateStaticParams(){ return publications.map(({slug}) => ({slug})); }
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata> { const {slug}=await params; const publication=publicationBySlug(slug); return publication ? {title:publication.title,description:publication.summary,openGraph:{title:publication.title,description:publication.summary,type:"article",publishedTime:publication.publishedAt}} : {}; }
export default async function PublicationPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const publication=publicationBySlug(slug);if(!publication)notFound();const related=relatedPublications(publication);const schema={"@context":"https://schema.org","@type":"Article",headline:publication.title,description:publication.summary,datePublished:publication.publishedAt,dateModified:publication.publishedAt,articleSection:publication.category,keywords:publication.tags.join(", "),publisher:{"@type":"Organization",name:"UNIFLUX-D Global Limited"},mainEntityOfPage:`https://unifluxdglobal.com/insights/${publication.slug}`};return <main className="print:bg-white"><ReadingProgress/><article><header className="bg-navy py-20 text-white md:py-28"><div className="container max-w-4xl"><Link href="/insights" className="print:hidden inline-flex items-center gap-2 text-sm font-bold text-gold hover:text-white"><span aria-hidden>←</span> All insights</Link><p className="eyebrow mt-10 !text-gold">{publication.type} · {publication.category}</p><h1 className="display mt-5 text-5xl font-semibold leading-[.98] md:text-7xl">{publication.title}</h1><p className="mt-7 max-w-2xl text-xl leading-8 text-slate-300">{publication.summary}</p><div className="mt-9 flex items-center justify-between border-t border-white/20 pt-5 text-sm text-slate-300"><span>{publication.readingTimeMinutes} min read</span><PrintButton /></div></div></header><div className="container max-w-3xl py-16 md:py-24"><p className="text-xs font-bold tracking-[.14em] text-slate uppercase">UNIFLUX-D Global Limited · Executive publication</p>{publication.body.map((section)=> <section className="mt-12 first:mt-0" key={section.heading}><h2 className="display text-3xl font-semibold leading-tight md:text-4xl">{section.heading}</h2>{section.paragraphs.map((paragraph)=><p className="mt-5 text-lg leading-8 text-slate" key={paragraph}>{paragraph}</p>)}</section>)}</div></article>{related.length > 0 && <section className="print:hidden bg-mist py-16"><div className="container"><p className="eyebrow">Continue reading</p><h2 className="display mt-4 text-3xl font-semibold">Related perspectives</h2><div className="mt-8 grid gap-4 md:grid-cols-3">{related.map((item)=><PublicationCard key={item.slug} publication={item}/>)}</div></div></section>}<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/></main>}
